name: ${APP_NAME}
services:
  php:
    depends_on:
      - db
    entrypoint: /var/www/html/entrypoint-symfony.sh
    env_file:
      - .env
    image: php:${PHP_VERSION}
    logging:
      driver: json-file
      options:
          max-size: "5m"
          max-file: "2"
    restart: always
    volumes:
      - ./app:/var/www/html
      - ./bin-cache:/bin-cache
  web:
    depends_on:
      - php
    image: caddy:2
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
    ports:
      - "80:80"
      - "443:443"
      - "444:444"
    restart: always
    volumes:
      - './caddy:/etc/caddy/'
      - ./app:/var/www/html
  db:
    env_file:
      - .env
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    image: postgres:${POSTGRES_VERSION}
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
    # ports:
    #   - "5432:5432"
    restart: always
    user: "${UID}:${GID}"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - /etc/passwd:/etc/passwd:ro
  # ide:
  #   image: codercom/code-server:latest
  #   restart: always
  #   user: "${UID}:${GID}"
  #   volumes:
  #     - ./ide_data/dot_local:/home/coder/.local
  #     - ./ide_data/dot_config:/home/coder/.config
  #     - ./app:/home/coder/project
  #   logging:
  #     driver: json-file
  #     options:
  #         max-size: "5m"
  #         max-file: "2"
#   db:
#       image: mysql:${MYSQL_VERSION}
#       restart: always
#       user: "${UID}:${GID}"
#       ports:
#         - "3306:3306"
#       volumes:
#         - mysql_data_vol:/var/lib/mysql
#       environment:
#         MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
#         MYSQL_DATABASE: "${MYSQL_DATABASE}"
#         MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
#       logging:
#         driver: json-file
#         options:
#             max-size: "5m"
#             max-file: "2"
# volumes:
#     mysql_data_vol: {}
